import math
from classes import Appliance
from appliances import nonShiftable, shiftable, auxilary

# * Prices generated by generateElectricityPrices.py
prices = {
    0: 0.1881189392916689,
    1: 0.15669587010083286,
    2: 0.18854491483107688,
    3: 0.17051124912599924,
    4: 0.18480647823538565,
    5: 0.19444184397657743,
    6: 0.1519431054522511,
    7: 0.1673067560873493,
    8: 0.15573301443004656,
    9: 0.1668444947332441,
    10: 0.15214300491480798,
    11: 0.19361587542377368,
    12: 0.18616869478749637,
    13: 0.19696996914739967,
    14: 0.18518044305777906,
    15: 0.19129745418602354,
    16: 0.5293345712561643,
    17: 0.4009143297603295,
    18: 0.3676248137850665,
    19: 0.5396424663349464,
    20: 0.41882110015883267,
    21: 0.1512023208075347,
    22: 0.15217288496241757,
    23: 0.15629241216427536
}


def estimate_electricity_cost_for_run(hour: int, duration: int, consumes: int) -> int:
    global prices
    cost = 0
    for i in range(hour, hour + duration):
        if i >= 24:
            i -= 24
        cost += prices[i] * (consumes / duration)
    return cost

# * DESCRIPTION: Estimates the electricity cost for a given hour
# * INPUT: hours: int, min: int, max: int
# * OUTPUT: int


def estimate_best_hour_start(duration: int, min_hour: int, max_hour: int, consumes: int) -> int:
    global prices

    min_cost = -1
    min_index = -1
    if max_hour < min_hour:
        max_hour += 24
    for hour in range(min_hour, max_hour - duration):
        if hour >= 24:
            hour -= 24
        cost = estimate_electricity_cost_for_run(hour, duration, consumes)
        if cost < min_cost or min_cost == -1:
            min_cost = cost
            min_index = hour

    return min_index

# * DESCRIPTION: Calculates the optimal schedule for the given appliances
# * INPUT: appliances: Appliance[] -> list of appliances
# * OUTPUT: dict -> {hour: Appliance[]}


def optimal_calculation(appliances):
    schedule = {}
    for i in range(24):
        schedule[i] = []

    # * Calculate optimal schedule
    for appliance in appliances:
        if not appliance.shiftable or ((appliance.timeStart + appliance.duration) % 24) == appliance.timeStop % 24:
            schedule[appliance.timeStart].append(appliance)
            continue

        hour_start = estimate_best_hour_start(
            appliance.duration, appliance.timeStart, appliance.timeStop, appliance.consumption)
        schedule[hour_start].append(appliance)

    return schedule


# * DESCRIPTION: Calculates total load for each hour based on all appliances, and peak hour + load
# * INPUT: appliances: Appliance[] -> list of appliances
# * OUTPUT: schedule: dict, peakHour: int, peakLoad: float

def calculate_peak_load(appliances):
    schedule = {}
    for i in range(24):
        schedule[i] = 0
    # Calculate total energy consumption for all appliances each hour
    for a in appliances:
        if not a.shiftable or ((a.timeStart + a.duration) % 24) == a.timeStop % 24:
            for i in range(24):
                schedule[i] += (a.consumption / 24)/1000
            continue
        hourStart = estimate_best_hour_start(
            a.duration, a.timeStart, a.timeStop, a.consumption
        )
        for i in range(hourStart, (hourStart + a.duration + 1)):
            schedule[i] += (a.consumption / a.duration)/1000
    # Find hour with highest energy consumption
    peakHour = 0
    peakPrice = schedule[peakHour]
    for hour in schedule.keys():
        if schedule[hour] > peakPrice:
            peakHour = hour
            peakPrice = schedule[peakHour]

    return schedule, peakHour, peakPrice


def scheduleAppliances(appliances):
    schedule = []
    for a in appliances:
        if not a.shiftable or ((a.timeStart + a.duration) % 24) == a.timeStop % 24:
            schedule.append({
                "name": a.name,
                "start": a.timeStart,
                "stop": a.timeStop,
                "duration": a.duration,
                "consumption": (a.consumption/a.duration)
            })
            continue
        optimalStartTime = estimate_best_hour_start(
            a.duration, a.timeStart, a.timeStop, a.consumption
        )
        schedule.append({
            "name": a.name,
            "start": optimalStartTime,
            "stop": a.timeStop,
            "duration": a.duration,
            "consumption": (a.consumption/a.duration)
        })

    # Sort schedule by appliance start time
    schedule = sorted(schedule, key=lambda x: x["start"])

    return schedule


def calculatePeak(schedule):
    hourlyTotalConsumption = {}
    totalCost = 0
    for i in range(24):
        hourlyTotalConsumption[i] = 0
    for appliance in schedule:
        for i in range(appliance["start"], (appliance["start"]+appliance["duration"])):
            hourlyTotalConsumption[i] += appliance["consumption"] / 1000
    peakHour = 0
    peakLoad = hourlyTotalConsumption[peakHour]
    for hour in hourlyTotalConsumption:
        if hourlyTotalConsumption[hour] > peakLoad:
            peakHour = hour
            peakLoad = hourlyTotalConsumption[peakHour]

    for x in schedule:
        totalCost += estimate_electricity_cost_for_run(
            x["start"], x["duration"], (x["consumption"] * x["duration"]) / 1000)

    return peakHour, peakLoad, totalCost


def applianceReference(appliance):
    for a in nonShiftable:
        if a == appliance["name"]:
            return nonShiftable[a]
    for a in shiftable:
        if a == appliance["name"]:
            return shiftable[a]
    for a in auxilary:
        if a == appliance["name"]:
            return auxilary[a]


def optimizeSchedule(schedule):
    # Create copy of schedule
    originalSchedule = schedule.copy()
    peakLoad = calculatePeak(originalSchedule)[1]
    totalCost = calculatePeak(originalSchedule)[2]
    lenght = len(originalSchedule)
    print("Incoming:")
    print("Peak load", peakLoad)
    print("Total cost", totalCost)

    for i in range(len(originalSchedule)):
        if originalSchedule[i]["duration"] == 24:
            continue
        appliance = originalSchedule.pop(i)
        ref = applianceReference(appliance)
        for j in range(ref[4], ref[5]-ref[3]):
            originalSchedule.append({
                "name": appliance["name"],
                "start": j,
                "stop": ref[5],
                "duration": ref[3],
                "consumption": appliance["consumption"]
            })
            newPeakLoad = calculatePeak(originalSchedule)[1]
            newTotalCost = calculatePeak(originalSchedule)[2]
            if newPeakLoad > peakLoad and newTotalCost > totalCost:
                del originalSchedule[-1]
            elif newPeakLoad < peakLoad:  # her skal det egt stå newPeakLoad < peakLoad AND newTotalCost < total cost, men da kommer det ingen endringer
                peakLoad = newPeakLoad
                totalCost = newTotalCost
                appliance = originalSchedule.pop()
            else:
                del originalSchedule[-1]

        if len(originalSchedule) < lenght:
            originalSchedule.append(appliance)

    peakLoad = calculatePeak(originalSchedule)[1]
    totalCost = calculatePeak(originalSchedule)[2]
    print("Outgoing:")
    print("Peak load", peakLoad)
    print("Total cost", totalCost)

    return originalSchedule


# * DESCRIPTION: Calculates the total daily energy consumption for the given schedule
# * INPUT: schedule: dict -> {hour: Appliance[]}
# * OUTPUT: int


def calculate_schedule_cost(schedule: dict) -> int:
    total = 0
    for hour in schedule:
        for appliance in schedule[hour]:
            total += estimate_electricity_cost_for_run(
                hour, appliance.duration, appliance.consumption)

    return round(total / 1000, 2)

# * DESCRIPTION: Prints the given schedule to the console
# * INPUT: schedule: dict -> {hour: Appliance[]}
# * OUTPUT: None


def print_schedule(schedule: dict) -> None:
    for hour in schedule.keys():
        if (len(schedule[hour]) == 0):
            continue
        for appliance in schedule[hour]:
            print(
                f'{f"{hour}:00-{hour + appliance.duration}:00":<11} - {appliance.name:<16} ({appliance.consumption / 1000} kW)')


def print_scedule_2(schedule):
    totalConsumption = 0
    totalCost = 0
    for x in schedule:
        totalConsumption += (x["consumption"] / 1000) * x["duration"]
        totalCost += estimate_electricity_cost_for_run(
            x["start"], x["duration"], (x["consumption"] * x["duration"])/1000)
        print(x["start"], ":00 -", (x["start"]+x["duration"]),
              ":00 ", x["name"], " - ", (x["consumption"] / 1000), "kWh")
    print("Total energy consumption:", round(totalConsumption, 4),
          "kWh\nTotal energy cost:", round(totalCost / 1000, 2), "nok")
